### ISSUE TITLE
Please enhance the docker build workflow to be triggered automatically on new release

### ISSUE THREAD

**Issue by anarion80** [appdev/siyuan-unlock#42]
Hello, 

As the title says, please enhance the docker image build workflow so that it triggers automatically on new release being published. Something like:

```yaml
on:
  release:
    types: [published]
```
